### ISSUE TITLE
urxvt-tabbedex doesn't play well with input methods.

### ISSUE THREAD

**Issue by yshui** [stepb/urxvt-tabbedex#18]
I witness several weird behaviour when using tabbedex with an input method (fcitx to be specific). 

To name some: 1) when the mouse pointer in not inside the window (but the window is still focused, like the pointer is hovering over the title bar), I can't input into urxvt. 2)If I hover my mouse over the input panel, urxvt lost input focus (It shouldn't, since the panel won't get focused), and thus interrupt the input sequence.

Don't know if this is tabbedex specific, since I have tested the original tabbed.

**Comment by mina86** [comment]
Sounds like a duplicate of #17 which is not tabbedex specific (happens also in tabbed). There are some patches for urxvt floating around that fix it.

**Comment by barul42** [comment]
Would you happen to have a patch that fix this? I can't find any and I still have the issue

**Comment by mina86** [comment]
I’ve included the patch in https://github.com/mina86/urxvt-tabbedex repository.

**Comment by barul42** [comment]
Thanks for the patch, I just tried it; it seems to have solved the PgUp/PgDn issue, but I still can't use the dead keys, as " or ^ unless my cursor is over the window. :(

**Comment by mina86** [comment]
Oh, I see. Yes, I can confirm that this patch does not fix problem with dead keys.

The work around I came up with is to configure WM to zap mouse pointer to the middle of the urxvt window when it’s focused using key shortcut. This doesn’t fix the issue but solves the problem for me.

**Comment by mina86** [comment]
Could you test again with https://github.com/mina86/urxvt-tabbedex and most recent version and rxvt-unicode? There were recently fixes pushed upstream to the terminal.

**Comment by barul42** [comment]
I did test with urxvt 9.22 from arch repos, still had the issue. 
Since then I switched to xfce4-terminal, hence the late response 

Le 9 août 2016 17:28:25 GMT+02:00, Michal Nazarewicz notifications@github.com a écrit :

> Could you test again with https://github.com/mina86/urxvt-tabbedex and
> most recent version and rxvt-unicode? There were recently fixes pushed
> upstream to the terminal.
> 
> ---
> 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/stepb/urxvt-tabbedex/issues/18#issuecomment-238590333

## 

barul

**Comment by daaugusto** [comment]
Hi @mina86,

For your information, I can still reproduce the bug with dead keys. I'm using perl 5.24.1, rxvt-unicode 9.22 and tried your latest version of tabbedex (089d0cb).

**Comment by mina86** [comment]
I can reproduce it with `tabbed` so this appears to be a bug upstream that tabbedex inherits.

PS. You should be using https://github.com/mina86/urxvt-tabbedex, stepb’s repository is pretty much abandoned.

**Comment by daaugusto** [comment]
Hi mina86, thanks for your reply. In fact, I'm already using the latest commit of your fork. You're right, this also happens to tabbed (by the way, a [bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=849922) has been submitted to the Debian bug tracking).

**Comment by mina86** [comment]
Sadly it’s unlikely I’ll have time to fix this so I’m waiting for patches or upstream fix.

**Comment by cvr** [comment]
Hi, I can confirm this bug still lingers. Basically either `tabbed` or `tabbedex` extensions will make certain deadkeys (namely ~ or ^) to stop working when the mouse pointer is outside URxvt's terminal window. Confirmed in Debian Stretch 9.9 with urxvt-9.22 and perl-5.24.1.

**Comment by daaugusto** [comment]
I gave up insisting on urxvt-tabbedex and now I'm very happy using urxvt with tmux.
